const GET_RELATIONSHIP_LIST = 'GET_RELATIONSHIP_LIST';
const GET_RELATIONSHIP = 'GET_RELATIONSHIP';
const UPDATE_RELATIONSHIP = 'UPDATE_RELATIONSHIP';
const CREATE_RELATIONSHIP = 'CREATE_RELATIONSHIP';
const SEARCH_RELATIONSHIP_IN_LIST = 'SEARCH_RELATIONSHIP_IN_LIST';

export {
  GET_RELATIONSHIP_LIST,
  GET_RELATIONSHIP,
  CREATE_RELATIONSHIP,
  UPDATE_RELATIONSHIP,
  SEARCH_RELATIONSHIP_IN_LIST,
};
