const GET_RELATIONSHIP_LIST_START = 'GET_RELATIONSHIP_LIST_START';
const GET_RELATIONSHIP_LIST_SUCCESS = 'GET_RELATIONSHIP_LIST_SUCCESS';
const GET_RELATIONSHIP_LIST_FAILURE = 'GET_RELATIONSHIP_LIST_FAILURE';
const GET_RELATIONSHIP_START = 'GET_RELATIONSHIP_START';
const GET_RELATIONSHIP_SUCCESS = 'GET_RELATIONSHIP_SUCCESS';
const GET_RELATIONSHIP_FAILURE = 'GET_RELATIONSHIP_FAILURE';
const CREATE_RELATIONSHIP_START = 'CREATE_RELATIONSHIP_START';
const CREATE_RELATIONSHIP_SUCCESS = 'CREATE_RELATIONSHIP_SUCCESS';
const CREATE_RELATIONSHIP_FAILURE = 'CREATE_RELATIONSHIP_FAILURE';
const UPDATE_RELATIONSHIP_START = 'UPDATE_RELATIONSHIP_START';
const UPDATE_RELATIONSHIP_SUCCESS = 'UPDATE_RELATIONSHIP_SUCCESS';
const UPDATE_RELATIONSHIP_FAILURE = 'UPDATE_RELATIONSHIP_FAILURE';
const SEARCHED_RELATIONSHIP = 'SEARCHED_RELATIONSHIP';

export {
  GET_RELATIONSHIP_LIST_START,
  GET_RELATIONSHIP_LIST_SUCCESS,
  GET_RELATIONSHIP_LIST_FAILURE,
  GET_RELATIONSHIP_START,
  GET_RELATIONSHIP_SUCCESS,
  GET_RELATIONSHIP_FAILURE,
  CREATE_RELATIONSHIP_START,
  CREATE_RELATIONSHIP_SUCCESS,
  CREATE_RELATIONSHIP_FAILURE,
  UPDATE_RELATIONSHIP_START,
  UPDATE_RELATIONSHIP_SUCCESS,
  UPDATE_RELATIONSHIP_FAILURE,
  SEARCHED_RELATIONSHIP,
};
