const GET_USER_LIST = 'GET_USER_LIST';
const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
const CREATE_USER = 'CREATE_USER';
const UPDATE_USER = 'UPDATE_USER';
const SEARCH_USER_IN_LIST = 'SEARCH_USER_IN_LIST';
const SORT_USERS = 'SORT_USERS';

export {
  GET_USER_LIST,
  CREATE_USER,
  UPDATE_USER,
  UPDATE_PASSWORD,
  SEARCH_USER_IN_LIST,
  SORT_USERS,
};
