const GET_AUTOGRAPH_LIST = 'GET_AUTOGRAPH_LIST';
const GET_AUTOGRAPH_APPROVALS_LIST = 'GET_AUTOGRAPH_APPROVALS_LIST';
const GET_AUTOGRAPH_ARCHIVES_LIST = 'GET_AUTOGRAPH_ARCHIVES_LIST';
const GET_AUTOGRAPH = 'GET_AUTOGRAPH';
const GET_AUTOGRAPH_STATUS = 'GET_AUTOGRAPH_STATUS';
const UPDATE_AUTOGRAPH_STATUS = 'UPDATE_AUTOGRAPH_STATUS';
const SEARCH_AUTOGRAPH_IN_LIST = 'SEARCH_AUTOGRAPH_IN_LIST';
const SORT_AUTOGRAPHS = 'SORT_AUTOGRAPHS';

export {
  GET_AUTOGRAPH_LIST,
  GET_AUTOGRAPH_APPROVALS_LIST,
  GET_AUTOGRAPH_ARCHIVES_LIST,
  GET_AUTOGRAPH,
  GET_AUTOGRAPH_STATUS,
  UPDATE_AUTOGRAPH_STATUS,
  SEARCH_AUTOGRAPH_IN_LIST,
  SORT_AUTOGRAPHS,
};
