const GET_AUTOGRAPH_LIST_START = 'GET_AUTOGRAPH_LIST_START';
const GET_AUTOGRAPH_LIST_SUCCESS = 'GET_AUTOGRAPH_LIST_SUCCESS';
const GET_AUTOGRAPH_LIST_FAILURE = 'GET_AUTOGRAPH_LIST_FAILURE';
const GET_AUTOGRAPH_STATUS_START = 'GET_AUTOGRAPH_STATUS_START';
const GET_AUTOGRAPH_STATUS_SUCCESS = 'GET_AUTOGRAPH_STATUS_SUCCESS';
const GET_AUTOGRAPH_STATUS_FAILURE = 'GET_AUTOGRAPH_STATUS_FAILURE';
const UPDATE_AUTOGRAPH_STATUS_START = 'UPDATE_AUTOGRAPH_STATUS_START';
const UPDATE_AUTOGRAPH_STATUS_SUCCESS = 'UPDATE_AUTOGRAPH_STATUS_SUCCESS';
const UPDATE_AUTOGRAPH_STATUS_FAILURE = 'UPDATE_AUTOGRAPH_STATUS_FAILURE';
const SEARCHED_AUTOGRAPH = 'SEARCHED_AUTOGRAPH';
const RESET_AUTOGRAPH_STATE = 'RESET_AUTOGRAPH_STATE';
const SORTED_AUTOGRAPHS = 'SORTED_AUTOGRAPHS';

const GET_AUTOGRAPH_APPROVALS_LIST_START = 'SORTED_AUTOGRAPHS';
const GET_AUTOGRAPH_APPROVALS_LIST_SUCCESS = 'GET_AUTOGRAPH_APPROVALS_LIST_SUCCESS';
const GET_AUTOGRAPH_APPROVALS_LIST_FAILURE = 'GET_AUTOGRAPH_APPROVALS_LIST_FAILURE';

const GET_AUTOGRAPH_ARCHIVES_LIST_START = 'GET_AUTOGRAPH_ARCHIVES_LIST_START';
const GET_AUTOGRAPH_ARCHIVES_LIST_SUCCESS = 'GET_AUTOGRAPH_ARCHIVES_LIST_SUCCESS';
const GET_AUTOGRAPH_ARCHIVES_LIST_FAILURE = 'GET_AUTOGRAPH_ARCHIVES_LIST_FAILURE';

export {
  GET_AUTOGRAPH_LIST_START,
  GET_AUTOGRAPH_LIST_SUCCESS,
  GET_AUTOGRAPH_LIST_FAILURE,

  GET_AUTOGRAPH_APPROVALS_LIST_START,
  GET_AUTOGRAPH_APPROVALS_LIST_SUCCESS,
  GET_AUTOGRAPH_APPROVALS_LIST_FAILURE,

  GET_AUTOGRAPH_ARCHIVES_LIST_START,
  GET_AUTOGRAPH_ARCHIVES_LIST_SUCCESS,
  GET_AUTOGRAPH_ARCHIVES_LIST_FAILURE,

  GET_AUTOGRAPH_STATUS_START,
  GET_AUTOGRAPH_STATUS_SUCCESS,
  GET_AUTOGRAPH_STATUS_FAILURE,
  UPDATE_AUTOGRAPH_STATUS_START,
  UPDATE_AUTOGRAPH_STATUS_SUCCESS,
  UPDATE_AUTOGRAPH_STATUS_FAILURE,
  SEARCHED_AUTOGRAPH,
  SORTED_AUTOGRAPHS,
  RESET_AUTOGRAPH_STATE,
};
