const GET_ARTIST_LIST = 'GET_ARTIST_LIST';
const GET_ARTIST = 'GET_ARTIST';
const GET_ARTIST_PROFILE = 'GET_ARTIST_PROFILE';
const UPDATE_ARTIST_PROFILE = 'UPDATE_ARTIST_PROFILE';
const SEARCH_ARTIST_IN_LIST = 'SEARCH_ARTIST_IN_LIST';
const SORT_ARTISTS = 'SORT_ARTISTS';

export {
  GET_ARTIST_LIST,
  GET_ARTIST,
  GET_ARTIST_PROFILE,
  UPDATE_ARTIST_PROFILE,
  SEARCH_ARTIST_IN_LIST,
  SORT_ARTISTS,
};
