const GET_ARTIST_LIST_START = 'GET_ARTIST_LIST_START';
const GET_ARTIST_LIST_SUCCESS = 'GET_ARTIST_LIST_SUCCESS';
const GET_ARTIST_LIST_FAILURE = 'GET_ARTIST_LIST_FAILURE';
const GET_ARTIST_PROFILE_START = 'GET_ARTIST_PROFILE_START';
const GET_ARTIST_PROFILE_SUCCESS = 'GET_ARTIST_PROFILE_SUCCESS';
const GET_ARTIST_PROFILE_FAILURE = 'GET_ARTIST_PROFILE_FAILURE';
const UPDATE_ARTIST_PROFILE_START = 'UPDATE_ARTIST_PROFILE_START';
const UPDATE_ARTIST_PROFILE_SUCCESS = 'UPDATE_ARTIST_PROFILE_SUCCESS';
const UPDATE_ARTIST_PROFILE_FAILURE = 'UPDATE_ARTIST_PROFILE_FAILURE';
const SEARCHED_ARTIST = 'SEARCHED_ARTIST';
const RESET_ARTIST_STATE = 'RESET_ARTIST_STATE';
const SORTED_ARTISTS = 'SORTED_ARTISTS';

export {
  GET_ARTIST_LIST_START,
  GET_ARTIST_LIST_SUCCESS,
  GET_ARTIST_LIST_FAILURE,
  GET_ARTIST_PROFILE_START,
  GET_ARTIST_PROFILE_SUCCESS,
  GET_ARTIST_PROFILE_FAILURE,
  UPDATE_ARTIST_PROFILE_START,
  UPDATE_ARTIST_PROFILE_SUCCESS,
  UPDATE_ARTIST_PROFILE_FAILURE,
  SEARCHED_ARTIST,
  SORTED_ARTISTS,
  RESET_ARTIST_STATE,
};
