const GET_CONFIGURATION = 'GET_CONFIGURATION';
const GET_CONFIGURATION_BY_NAME = 'GET_CONFIGURATION_BY_NAME';
const UPDATE_CONFIGURATION = 'UPDATE_CONFIGURATION';

export { GET_CONFIGURATION, GET_CONFIGURATION_BY_NAME, UPDATE_CONFIGURATION };
