const GET_CONFIGURATION_START = 'GET_CONFIGURATION_START';
const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATION_SUCCESS';
const GET_CONFIGURATION_FAILURE = 'GET_CONFIGURATION_FAILURE';
const GET_CONFIGURATION_BY_NAME_START = 'GET_CONFIGURATION_BY_NAME_START';
const GET_CONFIGURATION_BY_NAME_SUCCESS = 'GET_CONFIGURATION_BY_NAME_SUCCESS';
const GET_CONFIGURATION_BY_NAME_FAILURE = 'GET_CONFIGURATION_BY_NAME_FAILURE';
const UPDATE_CONFIGURATION_START = 'UPDATE_CONFIGURATION_START';
const UPDATE_CONFIGURATION_SUCCESS = 'UPDATE_CONFIGURATION_SUCCESS';
const UPDATE_CONFIGURATION_FAILURE = 'UPDATE_CONFIGURATION_FAILURE';

export {
  GET_CONFIGURATION_START,
  GET_CONFIGURATION_SUCCESS,
  GET_CONFIGURATION_FAILURE,
  GET_CONFIGURATION_BY_NAME_START,
  GET_CONFIGURATION_BY_NAME_SUCCESS,
  GET_CONFIGURATION_BY_NAME_FAILURE,
  UPDATE_CONFIGURATION_START,
  UPDATE_CONFIGURATION_SUCCESS,
  UPDATE_CONFIGURATION_FAILURE,
};
