const GET_NFTS_LIST = 'GET_NFTS_LIST';
const GET_NFTS_PRODUCTS_LIST = 'GET_NFTS_PRODUCTS_LIST';
const GET_NFTS = 'GET_NFTS';
const GET_NFTS_DETAIL = 'GET_NFTS_DETAIL';
const SEARCH_NFTS_IN_LIST = 'SEARCH_NFTS_IN_LIST';
const SORT_NFTS_PRODUCTS = 'SORT_NFTS_PRODUCTS';

export {
  GET_NFTS_LIST,
  GET_NFTS_PRODUCTS_LIST,
  GET_NFTS,
  GET_NFTS_DETAIL,
  SEARCH_NFTS_IN_LIST,
  SORT_NFTS_PRODUCTS,
};
