const GET_NFTS_PRODUCTS_LIST_START = 'GET_NFTS_PRODUCTS_LIST_START';
const GET_NFTS_PRODUCTS_LIST_SUCCESS = 'GET_NFTS_PRODUCTS_LIST_SUCCESS';
const GET_NFTS_PRODUCTS_LIST_FAILURE = 'GET_NFTS_PRODUCTS_LIST_FAILURE';
const GET_NFTS_LIST_START = 'GET_NFTS_LIST_START';
const GET_NFTS_LIST_SUCCESS = 'GET_NFTS_LIST_SUCCESS';
const GET_NFTS_LIST_FAILURE = 'GET_NFTS_LIST_FAILURE';
const GET_NFTS_DETAIL_START = 'GET_NFTS_DETAIL_START';
const GET_NFTS_DETAIL_SUCCESS = 'GET_NFTS_DETAIL_SUCCESS';
const GET_NFTS_DETAIL_FAILURE = 'GET_NFTS_DETAIL_FAILURE';
const SEARCHED_NFTS = 'SEARCHED_NFTS';
const RESET_NFTS_STATE = 'RESET_NFTS_STATE';
const SORTED_NFTS_PRODUCTS = 'SORTED_NFTS_PRODUCTS';

export {
  GET_NFTS_PRODUCTS_LIST_START,
  GET_NFTS_PRODUCTS_LIST_SUCCESS,
  GET_NFTS_PRODUCTS_LIST_FAILURE,
  GET_NFTS_LIST_START,
  GET_NFTS_LIST_SUCCESS,
  GET_NFTS_LIST_FAILURE,
  GET_NFTS_DETAIL_START,
  GET_NFTS_DETAIL_SUCCESS,
  GET_NFTS_DETAIL_FAILURE,
  SEARCHED_NFTS,
  SORTED_NFTS_PRODUCTS,
  RESET_NFTS_STATE,
};
