const SET_LINKS_START = 'SET_LINKS_START';
const SET_LINKS_SUCCESS = 'SET_LINKS_SUCCESS';
const SET_LINKS_FAILURE = 'SET_LINKS_FAILURE';

export { SET_LINKS_START, SET_LINKS_SUCCESS, SET_LINKS_FAILURE };
