const GET_DS_CUSTOMERS = 'GET_DS_CUSTOMERS';
const GET_DS_ARTISTS = 'GET_DS_ARTISTS';
const GET_DS_CHARACTERS = 'GET_DS_CHARACTERS';
const GET_DS_LICENSORS = 'GET_DS_LICENSORS';
const GET_DS_NFT = 'GET_DS_NFT';
const GET_DS_RECENT_PRODUCT = 'GET_DS_RECENT_PRODUCT';

export {
  GET_DS_CUSTOMERS,
  GET_DS_ARTISTS,
  GET_DS_CHARACTERS,
  GET_DS_LICENSORS,
  GET_DS_NFT,
  GET_DS_RECENT_PRODUCT,
};
