const GET_DS_CUSTOMERS_START = 'GET_DS_CUSTOMERS_START';
const GET_DS_CUSTOMERS_SUCCESS = 'GET_DS_CUSTOMERS_SUCCESS';
const GET_DS_CUSTOMERS_FAILURE = 'GET_DS_CUSTOMERS_FAILURE';
const GET_DS_ARTISTS_START = 'GET_DS_ARTISTS_START';
const GET_DS_ARTISTS_SUCCESS = 'GET_DS_ARTISTS_SUCCESS';
const GET_DS_ARTISTS_FAILURE = 'GET_DS_ARTISTS_FAILURE';
const GET_DS_CHARACTERS_START = 'GET_DS_CHARACTERS_START';
const GET_DS_CHARACTERS_SUCCESS = 'GET_DS_CHARACTERS_SUCCESS';
const GET_DS_CHARACTERS_FAILURE = 'GET_DS_CHARACTERS_FAILURE';
const GET_DS_LICENSORS_START = 'GET_DS_LICENSORS_START';
const GET_DS_LICENSORS_SUCCESS = 'GET_DS_LICENSORS_SUCCESS';
const GET_DS_LICENSORS_FAILURE = 'GET_DS_LICENSORS_FAILURE';
const GET_DS_NFT_START = 'GET_DS_NFT_START';
const GET_DS_NFT_SUCCESS = 'GET_DS_NFT_SUCCESS';
const GET_DS_NFT_FAILURE = 'GET_DS_NFT_FAILURE';
const GET_DS_RECENT_PRODUCT_START = 'GET_DS_RECENT_PRODUCT_START';
const GET_DS_RECENT_PRODUCT_SUCCESS = 'GET_DS_RECENT_PRODUCT_SUCCESS';
const GET_DS_RECENT_PRODUCT_FAILURE = 'GET_DS_RECENT_PRODUCT_FAILURE';

export {
  GET_DS_CUSTOMERS_START,
  GET_DS_CUSTOMERS_SUCCESS,
  GET_DS_CUSTOMERS_FAILURE,
  GET_DS_ARTISTS_START,
  GET_DS_ARTISTS_SUCCESS,
  GET_DS_ARTISTS_FAILURE,
  GET_DS_CHARACTERS_START,
  GET_DS_CHARACTERS_SUCCESS,
  GET_DS_CHARACTERS_FAILURE,
  GET_DS_LICENSORS_START,
  GET_DS_LICENSORS_SUCCESS,
  GET_DS_LICENSORS_FAILURE,
  GET_DS_NFT_START,
  GET_DS_NFT_SUCCESS,
  GET_DS_NFT_FAILURE,
  GET_DS_RECENT_PRODUCT_START,
  GET_DS_RECENT_PRODUCT_SUCCESS,
  GET_DS_RECENT_PRODUCT_FAILURE,
};
