const GET_LICENSOR_LIST = 'GET_LICENSOR_LIST';
const GET_LICENSOR = 'GET_LICENSOR';
const UPDATE_LICENSOR = 'UPDATE_LICENSOR';
const CREATE_LICENSOR = 'CREATE_LICENSOR';
const SEARCH_LICENSOR_IN_LIST = 'SEARCH_LICENSOR_IN_LIST';
const SORT_LICENSORS = 'SORT_LICENSORS';

export {
  GET_LICENSOR_LIST,
  GET_LICENSOR,
  CREATE_LICENSOR,
  UPDATE_LICENSOR,
  SEARCH_LICENSOR_IN_LIST,
  SORT_LICENSORS,
};
