const GET_LICENSOR_LIST_START = 'GET_LICENSOR_LIST_START';
const GET_LICENSOR_LIST_SUCCESS = 'GET_LICENSOR_LIST_SUCCESS';
const GET_LICENSOR_LIST_FAILURE = 'GET_LICENSOR_LIST_FAILURE';
const GET_LICENSOR_START = 'GET_LICENSOR_START';
const GET_LICENSOR_SUCCESS = 'GET_LICENSOR_SUCCESS';
const GET_LICENSOR_FAILURE = 'GET_LICENSOR_FAILURE';
const CREATE_LICENSOR_START = 'CREATE_LICENSOR_START';
const CREATE_LICENSOR_SUCCESS = 'CREATE_LICENSOR_SUCCESS';
const CREATE_LICENSOR_FAILURE = 'CREATE_LICENSOR_FAILURE';
const UPDATE_LICENSOR_START = 'UPDATE_LICENSOR_START';
const UPDATE_LICENSOR_SUCCESS = 'UPDATE_LICENSOR_SUCCESS';
const UPDATE_LICENSOR_FAILURE = 'UPDATE_LICENSOR_FAILURE';
const SEARCHED_LICENSOR = 'SEARCHED_LICENSOR';

export {
  GET_LICENSOR_LIST_START,
  GET_LICENSOR_LIST_SUCCESS,
  GET_LICENSOR_LIST_FAILURE,
  GET_LICENSOR_START,
  GET_LICENSOR_SUCCESS,
  GET_LICENSOR_FAILURE,
  CREATE_LICENSOR_START,
  CREATE_LICENSOR_SUCCESS,
  CREATE_LICENSOR_FAILURE,
  UPDATE_LICENSOR_START,
  UPDATE_LICENSOR_SUCCESS,
  UPDATE_LICENSOR_FAILURE,
  SEARCHED_LICENSOR,
};
