const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
const GET_CUSTOMER = 'GET_CUSTOMER';
const GET_CUSTOMER_PRODUCT_SERIAL = 'GET_CUSTOMER_PRODUCT_SERIAL';
const GET_CUSTOMER_PRODUCT_RECENT_PURCHASE
= 'GET_CUSTOMER_PRODUCT_RECENT_PURCHASE';
const GET_CUSTOMER_PRODUCT_OWNED
= 'GET_CUSTOMER_PRODUCT_OWNED';
const GET_CUSTOMER_PRODUCT_TRANSFERRED
= 'GET_CUSTOMER_PRODUCT_TRANSFERRED';
const GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES
= 'GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES';
const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
const SEARCH_CUSTOMER_IN_LIST = 'SEARCH_CUSTOMER_IN_LIST';
const SORT_CUSTOMERS = 'SORT_CUSTOMERS';
const SORT_CUSTOMERS_BY_QTY = 'SORT_CUSTOMERS_BY_QTY';

export {
  GET_CUSTOMER_LIST,
  GET_CUSTOMER,
  GET_CUSTOMER_PRODUCT_SERIAL,
  GET_CUSTOMER_PRODUCT_RECENT_PURCHASE,
  GET_CUSTOMER_PRODUCT_OWNED,
  GET_CUSTOMER_PRODUCT_TRANSFERRED,
  GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES,
  CREATE_CUSTOMER,
  UPDATE_CUSTOMER,
  SEARCH_CUSTOMER_IN_LIST,
  SORT_CUSTOMERS,
  SORT_CUSTOMERS_BY_QTY,
};
