const GET_CUSTOMER_LIST_START = 'GET_CUSTOMER_LIST_START';
const GET_CUSTOMER_LIST_SUCCESS = 'GET_CUSTOMER_LIST_SUCCESS';
const GET_CUSTOMER_LIST_FAILURE = 'GET_CUSTOMER_LIST_FAILURE';
const GET_CUSTOMER_START = 'GET_CUSTOMER_START';
const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
const GET_CUSTOMER_FAILURE = 'GET_CUSTOMER_FAILURE';
const GET_CUSTOMER_PRODUCT_SERIAL_START = 'GET_CUSTOMER_PRODUCT_SERIAL_START';
const GET_CUSTOMER_PRODUCT_SERIAL_SUCCESS = 'GET_CUSTOMER_PRODUCT_SERIAL_SUCCESS';
const GET_CUSTOMER_PRODUCT_SERIAL_FAILURE = 'GET_CUSTOMER_PRODUCT_SERIAL_FAILURE';
const GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_START = 'GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_START';
const GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_SUCCESS = 'GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_SUCCESS';
const GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_FAILURE = 'GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED';
const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START';
const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';
const UPDATE_CUSTOMER_START = 'UPDATE_CUSTOMER_START';
const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';
const SEARCHED_CUSTOMER = 'SEARCHED_CUSTOMER';
const SORTED_CUSTOMERS = 'SORTED_CUSTOMERS';
const SORTED_CUSTOMERS_BY_QTY = 'SORTED_CUSTOMERS_BY_QTY';

const GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_START = 'GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_START';
const GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_SUCCESS = 'GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_SUCCESS';
const GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_FAILURE = 'GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_FAILURE';

const GET_CUSTOMER_PRODUCT_OWNED_START = 'GET_CUSTOMER_PRODUCT_OWNED_START';
const GET_CUSTOMER_PRODUCT_OWNED_SUCCESS = 'GET_CUSTOMER_PRODUCT_OWNED_SUCCESS';
const GET_CUSTOMER_PRODUCT_OWNED_FAILURE = 'GET_CUSTOMER_PRODUCT_OWNED_FAILURE';

const GET_CUSTOMER_PRODUCT_TRANSFERRED_START = 'GET_CUSTOMER_PRODUCT_TRANSFERRED_START';
const GET_CUSTOMER_PRODUCT_TRANSFERRED_SUCCESS = 'GET_CUSTOMER_PRODUCT_TRANSFERRED_SUCCESS';
const GET_CUSTOMER_PRODUCT_TRANSFERRED_FAILURE = 'GET_CUSTOMER_PRODUCT_TRANSFERRED_FAILURE';

const GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_START = 'GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_START';
const GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_SUCCESS = 'GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_SUCCESS';
const GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_FAILURE = 'GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_FAILURE';

export {
  GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_START,
  GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_SUCCESS,
  GET_CUSTOMER_PRODUCT_RECENT_PURCHASE_FAILURE,
  GET_CUSTOMER_PRODUCT_OWNED_START,
  GET_CUSTOMER_PRODUCT_OWNED_SUCCESS,
  GET_CUSTOMER_PRODUCT_OWNED_FAILURE,
  GET_CUSTOMER_PRODUCT_TRANSFERRED_START,
  GET_CUSTOMER_PRODUCT_TRANSFERRED_SUCCESS,
  GET_CUSTOMER_PRODUCT_TRANSFERRED_FAILURE,
  GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_START,
  GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_SUCCESS,
  GET_CUSTOMER_PRODUCT_PURCHASE_HISTORIES_FAILURE,
  GET_CUSTOMER_LIST_START,
  GET_CUSTOMER_LIST_SUCCESS,
  GET_CUSTOMER_LIST_FAILURE,
  GET_CUSTOMER_START,
  GET_CUSTOMER_SUCCESS,
  GET_CUSTOMER_FAILURE,
  GET_CUSTOMER_PRODUCT_SERIAL_START,
  GET_CUSTOMER_PRODUCT_SERIAL_SUCCESS,
  GET_CUSTOMER_PRODUCT_SERIAL_FAILURE,
  GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_START,
  GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_SUCCESS,
  GET_CUSTOMER_PRODUCT_SERIAL_TRANSFERRED_FAILURE,
  CREATE_CUSTOMER_START,
  CREATE_CUSTOMER_SUCCESS,
  CREATE_CUSTOMER_FAILURE,
  UPDATE_CUSTOMER_START,
  UPDATE_CUSTOMER_SUCCESS,
  UPDATE_CUSTOMER_FAILURE,
  SEARCHED_CUSTOMER,
  SORTED_CUSTOMERS,
  SORTED_CUSTOMERS_BY_QTY,
};
