const GET_CHARACTER_LIST = 'GET_CHARACTER_LIST';
const GET_CHARACTER = 'GET_CHARACTER';
const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
const CREATE_CHARACTER = 'CREATE_CHARACTER';
const SEARCH_CHARACTER_IN_LIST = 'SEARCH_CHARACTER_IN_LIST';

export {
  GET_CHARACTER_LIST,
  GET_CHARACTER,
  CREATE_CHARACTER,
  UPDATE_CHARACTER,
  SEARCH_CHARACTER_IN_LIST,
};
