const GET_CHARACTER_LIST_START = 'GET_CHARACTER_LIST_START';
const GET_CHARACTER_LIST_SUCCESS = 'GET_CHARACTER_LIST_SUCCESS';
const GET_CHARACTER_LIST_FAILURE = 'GET_CHARACTER_LIST_FAILURE';
const GET_CHARACTER_START = 'GET_CHARACTER_START';
const GET_CHARACTER_SUCCESS = 'GET_CHARACTER_SUCCESS';
const GET_CHARACTER_FAILURE = 'GET_CHARACTER_FAILURE';
const CREATE_CHARACTER_START = 'CREATE_CHARACTER_START';
const CREATE_CHARACTER_SUCCESS = 'CREATE_CHARACTER_SUCCESS';
const CREATE_CHARACTER_FAILURE = 'CREATE_CHARACTER_FAILURE';
const UPDATE_CHARACTER_START = 'UPDATE_CHARACTER_START';
const UPDATE_CHARACTER_SUCCESS = 'UPDATE_CHARACTER_SUCCESS';
const UPDATE_CHARACTER_FAILURE = 'UPDATE_CHARACTER_FAILURE';
const SEARCHED_CHARACTER = 'SEARCHED_CHARACTER';

export {
  GET_CHARACTER_LIST_START,
  GET_CHARACTER_LIST_SUCCESS,
  GET_CHARACTER_LIST_FAILURE,
  GET_CHARACTER_START,
  GET_CHARACTER_SUCCESS,
  GET_CHARACTER_FAILURE,
  CREATE_CHARACTER_START,
  CREATE_CHARACTER_SUCCESS,
  CREATE_CHARACTER_FAILURE,
  UPDATE_CHARACTER_START,
  UPDATE_CHARACTER_SUCCESS,
  UPDATE_CHARACTER_FAILURE,
  SEARCHED_CHARACTER,
};
