const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
const GET_PRODUCT = 'GET_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const SEARCH_PRODUCT_IN_LIST = 'SEARCH_PRODUCT_IN_LIST';
const CREATE_DESIGN = 'CREATE_DESIGN';
const GET_DESIGNS = 'GET_DESIGNS';
const CREATE_SERIAL_NUMBER = 'CREATE_SERIAL_NUMBER';
const CREATE_PRODUCT_SERIES = 'CREATE_PRODUCT_SERIES';
const GET_SERIAL_NUMBERS = 'GET_SERIAL_NUMBERS';
const GET_PRODUCT_SERIES_LIST = 'GET_PRODUCT_SERIES_LIST';
const SORT_PRODUCTS = 'SORT_PRODUCTS';
const FILTER_PRODUCT_IN_LIST = 'FILTER_PRODUCT_IN_LIST';
const GET_RELATED_PRODUCT_LIST = 'GET_RELATED_PRODUCT_LIST';
const PREVIEW_DESIGN = 'PREVIEW_DESIGN';
const GET_SUSTAINABILITY_REPORT = 'GET_SUSTAINABILITY_REPORT';
const CREATE_SUSTAINABILITY_REPORT = 'CREATE_SUSTAINABILITY_REPORT';
const UPDATE_SUSTAINABILITY_REPORT = 'UPDATE_SUSTAINABILITY_REPORT';

export {
  GET_PRODUCT_LIST,
  GET_PRODUCT,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  SEARCH_PRODUCT_IN_LIST,
  CREATE_DESIGN,
  GET_DESIGNS,
  PREVIEW_DESIGN,
  CREATE_SERIAL_NUMBER,
  GET_SERIAL_NUMBERS,
  SORT_PRODUCTS,
  FILTER_PRODUCT_IN_LIST,
  GET_PRODUCT_SERIES_LIST,
  CREATE_PRODUCT_SERIES,
  GET_RELATED_PRODUCT_LIST,
  GET_SUSTAINABILITY_REPORT,
  CREATE_SUSTAINABILITY_REPORT,
  UPDATE_SUSTAINABILITY_REPORT,
};
