const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
const GET_PRODUCT = 'GET_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const SEARCH_PRODUCT_IN_LIST = 'SEARCH_PRODUCT_IN_LIST';
const CREATE_DESIGN = 'CREATE_DESIGN';
const GET_DESIGNS = 'GET_DESIGNS';
const CREATE_SERIAL_NUMBER = 'CREATE_SERIAL_NUMBER';
const GET_SERIAL_NUMBERS = 'GET_SERIAL_NUMBERS';

export {
  GET_PRODUCT_LIST,
  GET_PRODUCT,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  SEARCH_PRODUCT_IN_LIST,
  CREATE_DESIGN,
  GET_DESIGNS,
  CREATE_SERIAL_NUMBER,
  GET_SERIAL_NUMBERS,
};
