const GET_PRODUCT_LIST_START = 'GET_PRODUCT_LIST_START';
const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
const GET_PRODUCT_LIST_FAILURE = 'GET_PRODUCT_LIST_FAILURE';
const GET_PRODUCT_START = 'GET_PRODUCT_START';
const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';
const SEARCHED_PRODUCT = 'SEARCHED_PRODUCT';
const CREATE_DESIGN_START = 'CREATE_DESIGN_START';
const CREATE_DESIGN_SUCCESS = 'CREATE_DESIGN_SUCCESS';
const CREATE_DESIGN_FAILURE = 'CREATE_DESIGN_FAILURE';
const GET_DESIGNS_START = 'GET_DESIGNS_START';
const GET_DESIGNS_SUCCESS = 'GET_DESIGNS_SUCCESS';
const GET_DESIGNS_FAILURE = 'GET_DESIGNS_FAILURE';
const UPDATE_DESIGN_START = 'UPDATE_DESIGN_START';
const UPDATE_DESIGN_SUCCESS = 'UPDATE_DESIGN_SUCCESS';
const UPDATE_DESIGN_FAILURE = 'UPDATE_DESIGN_FAILURE';
const CREATE_SERIAL_NUMBER_START = 'CREATE_SERIAL_NUMBER_START';
const CREATE_SERIAL_NUMBER_SUCCESS = 'CREATE_SERIAL_NUMBER_SUCCESS';
const CREATE_SERIAL_NUMBER_FAILURE = 'CREATE_SERIAL_NUMBER_FAILURE';
const UPDATE_SERIAL_NUMBER_START = 'UPDATE_SERIAL_NUMBER_START';
const UPDATE_SERIAL_NUMBER_SUCCESS = 'UPDATE_SERIAL_NUMBER_SUCCESS';
const UPDATE_SERIAL_NUMBER_FAILURE = 'UPDATE_SERIAL_NUMBER_FAILURE';
const GET_SERIAL_NUMBERS_START = 'GET_SERIAL_NUMBERS_START';
const GET_SERIAL_NUMBERS_SUCCESS = 'GET_SERIAL_NUMBERS_SUCCESS';
const GET_SERIAL_NUMBERS_FAILURE = 'GET_SERIAL_NUMBERS_FAILURE';
const SORTED_PRODUCTS = 'SORTED_PRODUCTS';

export {
  GET_PRODUCT_LIST_START,
  GET_PRODUCT_LIST_SUCCESS,
  GET_PRODUCT_LIST_FAILURE,
  GET_PRODUCT_START,
  GET_PRODUCT_SUCCESS,
  GET_PRODUCT_FAILURE,
  CREATE_PRODUCT_START,
  CREATE_PRODUCT_SUCCESS,
  CREATE_PRODUCT_FAILURE,
  UPDATE_PRODUCT_START,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_FAILURE,
  SEARCHED_PRODUCT,
  SORTED_PRODUCTS,
  CREATE_DESIGN_START,
  CREATE_DESIGN_SUCCESS,
  CREATE_DESIGN_FAILURE,
  UPDATE_DESIGN_START,
  UPDATE_DESIGN_SUCCESS,
  UPDATE_DESIGN_FAILURE,
  GET_DESIGNS_START,
  GET_DESIGNS_SUCCESS,
  GET_DESIGNS_FAILURE,
  CREATE_SERIAL_NUMBER_START,
  CREATE_SERIAL_NUMBER_SUCCESS,
  CREATE_SERIAL_NUMBER_FAILURE,
  UPDATE_SERIAL_NUMBER_START,
  UPDATE_SERIAL_NUMBER_SUCCESS,
  UPDATE_SERIAL_NUMBER_FAILURE,
  GET_SERIAL_NUMBERS_START,
  GET_SERIAL_NUMBERS_SUCCESS,
  GET_SERIAL_NUMBERS_FAILURE,
};
