const GET_PERMISSION_LIST = 'GET_PERMISSION_LIST';
const GET_ROLE_LIST = 'GET_ROLE_LIST';
const CREATE_ROLE = 'CREATE_ROLE';
const EDIT_ROLE = 'EDIT_ROLE';
const DELETE_ROLE = 'DELETE_ROLE';
const EDIT_USER_ROLE = 'EDIT_USER_ROLE';
const GET_USER_ROLE = 'GET_USER_ROLE';
const ASSIGN_ROLE = 'ASSIGN_ROLE';

export {
  GET_PERMISSION_LIST,
  GET_ROLE_LIST,
  CREATE_ROLE,
  EDIT_ROLE,
  DELETE_ROLE,
  EDIT_USER_ROLE,
  GET_USER_ROLE,
  ASSIGN_ROLE,
};
