const GET_PERMISSION_LIST_START = 'GET_PERMISSION_LIST_START';
const GET_PERMISSION_LIST_SUCCESS = 'GET_PERMISSION_LIST_SUCCESS';
const GET_PERMISSION_LIST_FAILURE = 'GET_PERMISSION_LIST_FAILURE';
const GET_ROLE_LIST_START = 'GET_ROLE_LIST_START';
const GET_ROLE_LIST_SUCCESS = 'GET_ROLE_LIST_SUCCESS';
const GET_ROLE_LIST_FAILURE = 'GET_ROLE_LIST_FAILURE';
const CREATE_ROLE_START = 'CREATE_ROLE_START';
const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
const CREATE_ROLE_FAILURE = 'CREATE_ROLE_FAILURE';
const EDIT_ROLE_START = 'EDIT_ROLE_START';
const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
const EDIT_ROLE_FAILURE = 'EDIT_ROLE_FAILURE';
const DELETE_ROLE_START = 'DELETE_ROLE_START';
const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';
const EDIT_USER_ROLE_START = 'EDIT_USER_ROLE_START';
const EDIT_USER_ROLE_SUCCESS = 'EDIT_USER_ROLE_SUCCESS';
const EDIT_USER_ROLE_FAILURE = 'EDIT_USER_ROLE_FAILURE';
const GET_USER_ROLE_START = 'GET_USER_ROLE_START';
const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
const GET_USER_ROLE_FAILURE = 'GET_USER_ROLE_FAILURE';
const ASSIGN_ROLE_START = 'ASSIGN_ROLE_START';
const ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS';
const ASSIGN_ROLE_FAILURE = 'ASSIGN_ROLE_FAILURE';

export {
  GET_PERMISSION_LIST_START,
  GET_PERMISSION_LIST_SUCCESS,
  GET_PERMISSION_LIST_FAILURE,
  GET_ROLE_LIST_START,
  GET_ROLE_LIST_SUCCESS,
  GET_ROLE_LIST_FAILURE,
  CREATE_ROLE_START,
  CREATE_ROLE_SUCCESS,
  CREATE_ROLE_FAILURE,
  EDIT_ROLE_START,
  EDIT_ROLE_SUCCESS,
  EDIT_ROLE_FAILURE,
  DELETE_ROLE_START,
  DELETE_ROLE_SUCCESS,
  DELETE_ROLE_FAILURE,
  EDIT_USER_ROLE_START,
  EDIT_USER_ROLE_SUCCESS,
  EDIT_USER_ROLE_FAILURE,
  GET_USER_ROLE_START,
  GET_USER_ROLE_SUCCESS,
  GET_USER_ROLE_FAILURE,
  ASSIGN_ROLE_START,
  ASSIGN_ROLE_SUCCESS,
  ASSIGN_ROLE_FAILURE,
};
